name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build App
      run: fastlane beta
