name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Run tests
      run: xcodebuild clean test -project "Ceiba.xcodeproj" -scheme "Ceiba" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"
    - name: Build App
      run: xcodebuild -project "Ceiba.xcodeproj" -scheme "Ceiba" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
