name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    - name: Build App
      run: 
          xcodebuild -project "Ceiba.xcodeproj" -scheme "Ceiba" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
    - name: Run tests
      env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
      run: 
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild clean test -project "Ceiba.xcodeproj" -scheme "Ceiba" -destination "platform=$platform,name=$device"
